//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Restaurant_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderId { get; set; }
        public int quantity { get; set; }
        public decimal unitprice { get; set; }
        public System.DateTime orderdate { get; set; }
        public System.TimeSpan pickuptime { get; set; }
        public string userId { get; set; }
        public int foodId { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
